excluded:
 - Tests/*/XCTestManifests.swift
 - .build
 - .swiftpm

switch_case_alignment:
    indented_cases: true

disabled_rules:
 - force_cast
 - large_tuple
 - vertical_whitespace
 - trailing_whitespace
